language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: C/LNgw9xGZ+W6kxL6gyA65glR4ImDz9iLno12klMfkH3ma1+svUl8M6BheO3/Lp7mLHGDbgWmgfAiag+9gDcO4IKZNY5dfqBjxAi+LpeK8Ujo0zASKZNIR6YdSi2Z2TB18hQ2mtQ+zhENxJk6lP+CWkB288pLHbp2PG6rlYSZSVzGowEI4c+ciNLqyUZrY2/S2a57x5jxtu5Ky8FnDUAfcDh42Lqa8zeIAFE3kRilmx0SaYo7Rhq8ir2uy5pqHiaLGbpx6FKD0bqcQuoxIE1CzraML2TnKAIUv/dPJwcKwdlJJkb1Ry4JJFU0BUlaAshLAw0jpeggmbOvYJJQg2kFcnzhM5DY9scLpyVbfOD8HG/Vg63MyijToLkPLIfz+t4v+V/o2xE++Mx6NhJR+BZGDK3AhIf/Keei3Qpc7ZQDfX4scKjYTel7iiIzE47+fRKB7e7KKtdJmb/aXZSJ2TA6ouendb1VyQvyW+Nno5VdG4xDW9kSYMDFCuF1YMfkZTEige9JGGvczPgfq+ZE9pfL1igmrwSaBEQddk97d+0bHrvwh38fUrKjGd+JXowENvFePfnbo+UYgOZLntz1YB+Jppgou4fIBtP1c2I0GbZoB7BKgeASV0DIb1uSdJu+kTNuSfHit1juvmPtaRHt9S2/qYMkpk1OY03CGiN4s5hjbk=
  app:
    master: soundbroadcast
