language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: fuZZKXVznjiIaN/kdUOLnkGVlTaaoMOfO7CtQYY5EIRgoWXi1716IKGDvguD6A+OTk3Kko2skrRSp3FtyGbX0xstqSvsr4M9l3r1e8pGqqaWD6X3XNcS/1HB38QCHdC4YwDpwJunlBcQabgAO94MNDZv3OvOKPEk7Nlrp0NRbPZVB0MY8ByuVzZeywOtXFD1mdR/0tKMrVsFzFY4leJoG+W6DQmVcmUNU1QmLukHuzULTjbBRl/KJ+UgRvmknzExDyfxJ8mrsjMCCftAkXh+QeEFUMXpMUAwhZnSOC4N2NQeFLFgwFmhIDxvN8JOClI0QIP/QcpO8w6E/7Iwp3mF/rjEJGMJmJp+6SxlqBOofXaJgdiXjZqr9Qn7wdx6jBh04Wa8l+sqOCNexVobBVLPYj00+GlXj9XLlRbjVy+66emtOKWBsTbY0CN4ms82njHiePMK6bzexvfM467BJB99JuWpxuxP8ZuNGSE6YMhDUnjLZnS6L4yILq2td35is5PngavGB5u9pcQ1ZsjZJFuNxiZg/urN9hdnk1fFJMiRiCzYUFUbZ16sP/yKZxLQ7OSq+LwlsveE/hE3AwYsBZOqjUIDjz0XWTjaSMIgAw+IGOx7GoS2aevF8HXgTmmmE32OlJ6gIub0ywFRsYTP53nOLs0wcn4QP4SoCQpLYjiYjhA=
  app: soundbroadcast
  on:
    repo: Koen028/soundbroadcast
